### PR TITLE
Added GPLv3 License file

### PR DESCRIPTION
**Pull request by andir**
As discussed in #29 we would like to add a LICENSE file. This PR contains a GPLv3 license file as it can be found on the GNU website (https://www.gnu.org/licenses/gpl.txt)

I guess we might need all contributors to give their formal "OK" on the addition/change of LICENSE?

The current list of people would the be

- [x] @thekroko 
- [x] @Donutttt
- [x] @burfo 
- [ ] @jearle
- [ ] @gp2015
- [ ] @Electrosyrinx
- [x] @andir

### CODE REVIEW

**Comment by thekroko** [comment]
OK

**Comment by OliverRadini** [comment]
OK

**Comment by burfo** [comment]
Fine by me; I checked off my name.

**Comment by andir** [comment]
@jearle @gp2015 @Electrosyrinx you could please state your point on this ? :-)

**Comment by thekroko** [comment]
I'd vote for proceeding with adding the license if there is no further response within the next 2 days

**Pull request merged**
