### PR TITLE
add step to install angular/cli

### PR DESCRIPTION
**Pull request by rafriki**

### CODE REVIEW

**Comment by andir** [comment]
`angular-cli` is already listed as dependency https://github.com/thekroko/uthgard-herald/blob/master/herald/package.json#L38 why is this still required?

**Comment by rafriki** [comment]
I think it should be installed globally?

**Comment by andir** [comment]
Why should that be? If I only need that for this project does it make sense to install it globally? What happens if I need two different versions for two projects?

**Comment by burfo** [comment]
I agree with @andir , a developer isn't required to install it globally just to run this project.

**Comment by rafriki** [comment]
Okidoki

**Pull request closed without merging**
